wandb_version: 1

epochs:
  desc: null
  value: 5
batch_size:
  desc: null
  value: 8
lr:
  desc: null
  value: 0.0003
weight_b:
  desc: null
  value: 0.1
weight_p:
  desc: null
  value: 1
weight_c:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    python_version: 3.10.16
    cli_version: 0.16.0
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1742560394.367175
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.10.16
      5: 0.16.0
      8:
      - 5
      13: linux-x86_64
