wandb_version: 1

epochs:
  desc: null
  value: 1
batch_size:
  desc: null
  value: 1
lr:
  desc: null
  value: 0.0003
weight_b:
  desc: null
  value: 1
weight_p:
  desc: null
  value: 1
weight_c:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.6.13
    cli_version: 0.15.11
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1737551251.050864
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 3
      - 8
      - 16
      - 23
      4: 3.6.13
      5: 0.15.11
      8:
      - 5
      10:
      - 9
      13: linux-x86_64
