wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.13
    start_time: 1741094377.582875
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 3
      - 8
      - 16
      - 23
      4: 3.6.13
      5: 0.13.5
      8:
      - 5
      10:
      - 9
batch_size:
  desc: null
  value: 1
epochs:
  desc: null
  value: 250
lr:
  desc: null
  value: 0.0003
weight_b:
  desc: null
  value: 0.1
weight_c:
  desc: null
  value: 1
weight_p:
  desc: null
  value: 1
